### ISSUE TITLE
JAVA_ENABLE_DEBUG for jdk 11 is not valid.

### ISSUE THREAD

**Issue by survivant** [fabric8io-images/run-java-sh#101]
I modify my dockfile for this  (my port is 8181, not 8080 for my example)

EXPOSE 5005 8181

and I ran this command : (we see that the port 5005 was setted)
```

C:\workspace\hello>docker run -i --rm -p 8181:8181 -p 5005:5005 -e JAVA_ENABLE_DEBUG="true" hello
exec java -Dquarkus.http.host=0.0.0.0 -Djava.util.logging.manager=org.jboss.logmanager.LogManager -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005 -XX:+UseParallelGC -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -XX:MinHeapFreeRatio=20 -XX:MaxHeapFreeRatio=40 -XX:+ExitOnOutOfMemoryError -cp . -jar /deployments/app.jar
Listening for transport dt_socket at address: 5005
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/deployments/lib/ch.qos.logback.logback-classic-1.2.3.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/deployments/lib/org.jboss.slf4j.slf4j-jboss-logging-1.2.0.Final.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]
__  ____  __  _____   ___  __ ____  ______
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/
2020-04-07 13:02:16,542 INFO  [io.quarkus] (main) hello 1.0.0-SNAPSHOT (powered by Quarkus 1.3.1.Final) started in 2.732s. Listening on: http://0.0.0.0:8181
2020-04-07 13:02:16,544 INFO  [io.quarkus] (main) Profile prod activated.
2020-04-07 13:02:16,545 INFO  [io.quarkus] (main) Installed features: [cdi, hibernate-validator, kubernetes, rest-client, resteasy, resteasy-jackson, resteasy-jsonb, smallrye-context-propagation, smallrye-fault-tolerance, smallrye-health, smallrye-metrics, smallrye-openapi, spring-boot-properties, spring-di, spring-web, swagger-ui]
```

in docker ps I see this

0.0.0.0:5005->5005/tcp, 0.0.0.0:8181->8181/tcp

when I try to attach to the port 5005 I obtain this error  (in Intellij)

Error running 'quarkus ': Unable to open debugger port (localhost:5005): java.io.IOException "handshake failed - connection prematurally closed"

in IntelliJ, I have

Attach to remote JVM
socket
host : localhost   port 5005
-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005

It might be a bug in the run script, since for Java 11 it should have added

**-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005**

instead of

-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005

**Comment by survivant** [comment]
the workaround for now, is modify the JAVA_OPTIONS to include the port and not passing the variable

ENV JAVA_OPTIONS="-Dquarkus.http.host=0.0.0.0 -Djava.util.logging.manager=org.jboss.logmanager.LogManager -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"

**Comment by rhuss** [comment]
I think for Java 11 it doesn't really matter how to specify the `address` field:

```
$ java -version
java version "11.0.6" 2020-01-14 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.6+8-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.6+8-LTS, mixed mode)

$ java -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 -jar random-generator-runner.jar
Listening for transport dt_socket at address: 5005
__  ____  __  _____   ___  __ ____  ______
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/
2020-04-07 17:16:33,254 INFO  [io.quarkus] (main) random-generator 2.0 (powered by Quarkus 1.3.1.Final) started in 0.885s. Listening on: http://0.0.0.0:8080
2020-04-07 17:16:33,278 INFO  [io.quarkus] (main) Profile prod activated.
2020-04-07 17:16:33,278 INFO  [io.quarkus] (main) Installed features: [cdi, resteasy, resteasy-jsonb, smallrye-health]
^C2020-04-07 17:16:34,352 INFO  [io.quarkus] (main) random-generator stopped in 0.035s

$ java -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005 -jar random-generator-runner.jar
Listening for transport dt_socket at address: 5005
__  ____  __  _____   ___  __ ____  ______
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/
2020-04-07 17:16:39,510 INFO  [io.quarkus] (main) random-generator 2.0 (powered by Quarkus 1.3.1.Final) started in 0.759s. Listening on: http://0.0.0.0:8080
2020-04-07 17:16:39,532 INFO  [io.quarkus] (main) Profile prod activated.
2020-04-07 17:16:39,533 INFO  [io.quarkus] (main) Installed features: [cdi, resteasy, resteasy-jsonb, smallrye-health]
2020-04-07 17:16:40,942 INFO  [io.quarkus] (main) random-generator stopped in 0.033s
```

However it could be that for Java 11 binding with a `--adress=5005` only binds to localhost, which won't work in Docker container.

We should address that in `run-java.sh` and generate a different options depending on the Java version.

Would you mind to add an issue over there https://github.com/fabric8io-images/run-java-sh ? (that's the startup script). Thanks !

**Comment by survivant** [comment]
it's not what I did already ?  https://github.com/fabric8io-images/run-java-sh/issues/101   did you give me the right url ?

**Comment by rhuss** [comment]
ah, sorry. Was totally confused (to much on plate these days), thought this issue was opened against https://github.com/fabric8io-images/java . My bad, sorry. Will try to add this asap, but if you would like to give a try and send in pull request, this could speed up things.

**Comment by survivant** [comment]
here : https://github.com/fabric8io-images/run-java-sh/pull/102

**Comment by survivant** [comment]
@rhuss does the PR look ok to you ?

**Comment by rhuss** [comment]
Had no time to review it, but should happen towards the end of the week.

**Comment by survivant** [comment]
I'm back to follow up :)

**Comment by survivant** [comment]
I think we will be able to close this defect
