### ISSUE TITLE
alpine-OpenJDK11 unable to get Major java version

### ISSUE THREAD

**Issue by survivant** [fabric8io-images/run-java-sh#103]
there is a issue while parsing the java version 

I edited the script to add  set -x at the top

here the part where it extract the version
```
+ init_java_major_version
+ '[' -z  ]
+ local 'full_version='
+ '[' -n jdk-11.0.6+10 ]
+ full_version=jdk-11.0.6+10
+ echo jdk-11.0.6+10
+ sed -e 's/\(1\.\)\{0,1\}\([0-9]\{1,\}\).*/\2/'
+ export 'JAVA_MAJOR_VERSION=jdk-11'
```

the result is this when validation if the version is greaterThan.  

sh: jdk-11: out of range
sh: jdk-11: out of range
sh: jdk-11: out of range

```
bash-5.0$ java -version
openjdk version "11.0.6" 2020-01-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.6+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.6+10, mixed mode)
bash-5.0$
```

the environnement variable is : 
`JAVA_VERSION=jdk-11.0.6+10`

**Comment by survivant** [comment]
this regex work with openJDK  
JAVA_VER=$(java -version 2>&1 >/dev/null | egrep "\S+\s+version" | awk '{print $3}' | tr -d '"')

**Comment by survivant** [comment]
@rhuss do you think, you can take a look ?  I'll like to do a PR for Quarkus to use the next release of run-java-sh

**Comment by rhuss** [comment]
will check now

**Comment by rhuss** [comment]
Which image has JAVA_VERSION set to `jdk-11.0.6.+10` ? I mean run-java.sh can perfectly parse the output of `java -version` on alpine jdk, its just that JAVA_VERSION takes precedence and I'm curious where it comes from (the fabric8 images do not set it that way)

**Comment by rhuss** [comment]
It's this part that extract the JAVA_VERSION

```bash
 # Parse JAVA_VERSION variable available in containers
        if [ -n "${JAVA_VERSION:-}" ]; then
            full_version="$JAVA_VERSION"
        elif [ -n "${JAVA_HOME:-}" ] && [ -r "${JAVA_HOME}/release" ]; then
            full_version="$(grep -e '^JAVA_VERSION=' ${JAVA_HOME}/release | sed -e 's/.*\"\([0-9.]\{1,\}\).*/\1/')"
        else
            full_version=$(java -version 2>&1 | head -1 | sed -e 's/.*\"\([0-9.]\{1,\}\).*/\1/')
        fi
```

**Comment by rhuss** [comment]
I can make the regexp a bit more tolerant to cover that `jdk-` prefix and `+10` suffix, too but still curious where you see that JAVA_VERSION var.

**Comment by rhuss** [comment]
> this regex work with openJDK
> JAVA_VER=$(java -version 2>&1 >/dev/null | egrep "\S+\s+version" | awk '{print $3}' | tr -d '"')

```
echo "jdk-11.0.6+10" | egrep "\S+\s+version" | awk '{print $3}' | tr -d '"'
```

does not yield the proper result. The reason is not the regexp (that works in run-java.sh), toom but the fact that JAVA_VERSION takes precedence of `java -version`, also for performance reasons (to not unnecessarily call the JVM if not needed).

**Comment by survivant** [comment]
I came from this docker image : FROM adoptopenjdk/openjdk11:jdk-11.0.6_10-alpine


the dockerfile below was created for Quarkus (except that I had to change the docker image)
```
FROM adoptopenjdk/openjdk11:jdk-11.0.6_10-alpine

ARG JAVA_PACKAGE=java-11-openjdk-headless
ARG RUN_JAVA_VERSION=1.3.6

ENV LANG='en_US.UTF-8' LANGUAGE='en_US:en'

# Install java and the run-java script
# Also set up permissions for user `1001`
RUN apk add openssl curl ca-certificates \
    && mkdir /deployments \
    && chown 1001 /deployments \
    && chmod "g+rwX" /deployments \
    && chown 1001:root /deployments \
    && curl https://repo1.maven.org/maven2/io/fabric8/run-java-sh/${RUN_JAVA_VERSION}/run-java-sh-${RUN_JAVA_VERSION}-sh.sh -o /deployments/run-java.sh \
    && chown 1001 /deployments/run-java.sh \
    && chmod 540 /deployments/run-java.sh


COPY target/lib/* /deployments/lib/
COPY target/*-runner.jar /deployments/app.jar


#with debug port
EXPOSE 8181 5005

USER 1001

ENTRYPOINT [ "/deployments/run-java.sh" ]
```

**Comment by rhuss** [comment]
I see. Let me merge #105 and create a new release ....

**Comment by rhuss** [comment]
Just released https://github.com/fabric8io-images/run-java-sh/releases/tag/1.3.8 with the fix.
