### ISSUE TITLE
Infinite loop in `get_exec_args` with JAVA_APP_NAME set on Alpine linux

### ISSUE THREAD

**Issue by brenuart** [fabric8io-images/run-java-sh#20]
The check to verify whether the current shell supports `exec -a` seems to go crazy in an infinite loop when executed under Alpine Linux.

I'm not an expert in Alpine but as far as I can tell, the Alpine version of `/bin/bash` doesn't seem to support `exec -a` - hence the infinite loop.

**Comment by rhuss** [comment]
Currently I can't reproduce it. It also seems strange that the option `-a` would cause such an error as its only to set the name. 

I just tuned the behaviour with #42 and added a test. Could you check whether this fixes your use case ?

**Comment by brenuart** [comment]
This issue is rather old. I propose to close it.
