### ISSUE TITLE
Use experimental JDK support for cgroup memory limits in container

### ISSUE THREAD

**Issue by astefanutti** [fabric8io-images/run-java-sh#26]

**Comment by Hellspam** [comment]
I checked into using them - basically, they do the same thing as this script does, but you can only set the memory by fractions - so you can only have 1/n of the memory, meaning  100%, 50%, etc.
This script allows you to define different fractions.

**Comment by astefanutti** [comment]
The idea here is to use the JDK default, yet still exposing the `JAVA_MAX_MEM_RATIO` environment variable to define the heap size ratio. So that changes the default ratio being used, not the ability to define the ratio as a percentage. 

FWIW, new options are to be introduced that meet that need:
* https://bugs.openjdk.java.net/browse/JDK-8186248
* https://bugs.openjdk.java.net/browse/JDK-8186315

**Comment by Hellspam** [comment]
Yeah, who knows when they will come to the oracle jdk we have to use... 
Besides, since this script basically does the same thing as the internal JDK calculation, and if there is no cgroup limit, the flags won't do nothing, then I don't see the point in adding it

**Comment by astefanutti** [comment]
> Yeah, who knows when they will come to the oracle jdk we have to use...

This is orthogonal to that PR.

> Besides, since this script basically does the same thing as the internal JDK calculation, and if there is no cgroup limit, the flags won't do nothing, then I don't see the point in adding it

The point is to use the default heap size ergonomic.
