### ISSUE TITLE
Container limits not working correctly

### ISSUE THREAD

**Issue by Hellspam** [fabric8io-images/run-java-sh#32]
Hi, 
I've recently added this script to our docker images.
In our company we are using [nomad](https://www.nomadproject.io/).
When defining a limit on a container, it seems that both cgroup limits are set to the same value:
``
root@a1e73666d333:/# cat /sys/fs/cgroup/memory/memory.memsw.limit_in_bytes
14881390592
root@a1e73666d333:/# cat /sys/fs/cgroup/memory/memory.limit_in_bytes
14881390592
``

This causes the script to not calculate the memory limit for our heap correctly.
For now, I have removed the upper bound check, and the script works fine again.
Are you sure that it is correct to check the memory.memsw.limit_in_bytes as the upper limit? '
Shouldn't we use something like the memory of the host?
```
free -b | sed -n 2p | awk '$1=$1' | cut -d' ' -f2
```
Returns the total memory the host has for example.

**Comment by astefanutti** [comment]
@Hellspam I've just started working on it. Let me know if you plan to submit a PR and I'll stop working on it.

**Comment by Hellspam** [comment]
I can do the PR, as I am working on it for our docker images anyway.
WDYT about using free instead?

**Comment by Hellspam** [comment]
Ah, now I get what @rhuss  was trying to achieve.
The issue is when we do not set any limits, both values are impossibly high, which if we try to use as max mem, won't make any sense:
```
/ # cat /sys/fs/cgroup/memory/memory.limit_in_bytes 
9223372036854771712
/ # cat /sys/fs/cgroup/memory/memory.memsw.limit_in_bytes 
9223372036854771712
```

We could use something like this guy has defined:

**Comment by astefanutti** [comment]
On my side, I get the value 9223372036854771712 or 0x7FFFFFFFFFFFF000. The default value
in pages is (LONG_MAX / PAGE_SIZE), or 0x7FFFFFFFFFFFF, multiplied by PAGE_SIZE (i.e. 4096). I would first make sure we cannot rely on that. Otherwise, relying on `/proc/meminfo` seems a decent alternative.

/cc @rhuss

**Comment by Hellspam** [comment]
I don't get where you see the default value.
Anyway, from a quick search, it seems to get the LONG_MAX you have to use [perl](https://stackoverflow.com/questions/2965761/find-maximum-positive-integer-value-in-bourne-shell) (eww).
The LONG_MAX on my machine is:
``
LONG_MAX=9223372036854775807
``
I didn't find how it relates to the max CGROUP though, other than LONG_MAX - MAX_CGROUP = PAGE_SIZE - 1 (4095).
Also, from reading up on cgroups, it seems the cgroup value can also be -1 which disables the limit, so we should handle this case as well.
I will try to add that case this weekend.
> memory.limit_in_bytes
> Specifies the maximum usage permitted for user memory including the file cache. The default units are  bytes, but you can also specify a k or K, m or M, and g or G suffix for kilobytes, megabytes, and  gigabytes respectively. A value of -1 removes the limit.

**Comment by astefanutti** [comment]
> I don't get where you see the default value.

    $ docker run --rm openjdk:9 cat /sys/fs/cgroup/memory/memory.memsw.limit_in_bytes
    9223372036854771712

> Anyway, from a quick search, it seems to get the LONG_MAX you have to use perl (eww).

I haven't yet find an easy way to retrieve that constant. There are other ways than Perl, yet they introduce dependencies.

**Comment by rhuss** [comment]
I think we can close this now, thanks everyone for fixing this.
