### ISSUE TITLE
Versions later than 1.2.2 not available in public maven-repos

### ISSUE THREAD

**Issue by christopherfrieler** [fabric8io-images/run-java-sh#84]
Hi,

our build fails to download the latest version of run-java-sh. And on [https://search.maven.org/search?q=a:run-java-sh](https://search.maven.org/search?q=a:run-java-sh) the newest version is 1.2.2.

Where did you deploy the 1.3.x versions? Are they available in any public maven repository?

**Comment by christopherfrieler** [comment]
Having a closer look I found that in the pom.xml the version is still 1.2-SNAPSHOT. Seems like someone tagged the 1.3.x versions, but did not perform the maven release at all.

**Comment by rhuss** [comment]
Ah right. Sorry, totally messed up the release process (as I did just a release git release tag for the script which typically is consumed directly from GitHub).

Totally forgot the Maven artefact.

**Comment by rhuss** [comment]
Just released 1.3.4 (with no functional change to 1.3.3) and pushed to Maven central (should be pop up soon). Thanks for the heads-up !

**Comment by christopherfrieler** [comment]
Works. Thank you for the quick fix!
