### ISSUE TITLE
How to add bash shell to a docker azul/zulu-openjdk-alpine image to execute run-java.sh

### ISSUE THREAD

**Issue by fabri1983** [fabric8io-images/run-java-sh#95]
Hi. No Linux expert here.
I'm trying to execute the `run-java.sh` script from an `azul/zulu-openjdk-alpine:8u232-jre-headless` docker image. The last command of my dockerfile is:
```sh
CMD JAVA_OPTIONS="${JAVA_OPTS} ${ENV_JAVA_MODULES_FOR_HAZELCAST}" \
    JAVA_APP_DIR=/app \
    JAVA_CLASSPATH=/app/WEB-INF/classes:/app/WEB-INF/lib/*:/app/WEB-INF/lib-provided/* \
    JAVA_MAIN_CLASS=${ENV_JAVA_MAIN_CLASS} \
    /app/run-java.sh
```
(it previously had a COPY command from another staging step which copies all my app files to /app/)

However I'm getting next message when running the container:
```sh
/bin/sh: /app/run-java.sh: not found
```
Which is expected since there is no bash shell coming within the zulu's image.
So I tried to download a bash by adding next docker command:
```sh
RUN apk add --no-cache bash
```
But same error message appears.

So, **what in addition to bash tool do I need to add in order to fully support all internal commands used in run-java.sh script?**

Thanks in advance.

**Comment by rhuss** [comment]
Alpine typically comes with `ash` instead of `bash`, but run-java.sh should also work with ash seamlessly (so no need to install bash).

The error you get indicates, that you forgot to add the script into your image. I suggest to add a 

```
ADD run-java.sh /app/run-java.sh
```

to your Dockerfile after you have download [run-java.sh](https://github.com/fabric8io-images/run-java-sh/tree/master/fish-pepper/run-java-sh/fp-files) and stored it in your local directory.

**Comment by fabri1983** [comment]
The script is already on the image. I'll try with ash. Thanks for the reply!

**Comment by rhuss** [comment]
you can also try to run `docker run -it yourimage ash` and then try the script interactively. I suspect that the path is wrong (so no /app/run-java.sh is there as the error message indicates).

**Comment by fabri1983** [comment]
Hi. Definitely is an issue with the mini java 11 runtime built in a previous stage. The java executable is only 8888 bytes. When running an interactive shell over the container and calling `$JAVA_HOME/bin/java -version` it throws `/bin/ash: java: not found`. The executable is there, but its size tells me something went wrong during the creation of the java mini runtime in previous stage.
I'll close the issue since is not related to azul's zulu jvm nor run-java.sh script.
