### ISSUE TITLE
Pushing run-java.sh to Maven Central as an additional qualified artifact

### ISSUE THREAD

**Issue by gsmet** [fabric8io-images/run-java-sh#96]
Hey there,

I was wondering if you could consider pushing `run-java.sh` to Maven Central as a separate artifact with a special qualifier so that we can download the file directly from Maven Central without having to get the jar, unzip it and go deep inside the hierarchy?

Thanks.

-- 
Guillaume

**Comment by rhuss** [comment]
This exists and there is even a helpe class included which helps you to extract the shell script to an arbitrary place: https://github.com/fabric8io-images/run-java-sh#maven-builds

**Comment by rhuss** [comment]
You mean for having a direct download URL ? Would a GitHub URL also good enough  (like https://raw.githubusercontent.com/fabric8io-images/run-java-sh/v1.3.4/fish-pepper/run-java-sh/fp-files/run-java.sh) . Ok, could be prettier (e.g. as a release download).

But very likely I don't understand the use case properly ;) Maybe you could elaborate a bit on it ?

I will add the plain script as artefact for the next release, too. (BTW, not sure when I did the last Maven-based release, so have to check that, too)

**Comment by rhuss** [comment]
@gsmet could you please have a brief look at the PR https://github.com/fabric8io-images/run-java-sh/pull/97 ? If this ok (e.g. the filename looks like `run-java-sh-1.3.5-sh.sh` with classified `sh`), then I would merge and make a 1.3.5 release asap.

**Comment by cescoffier** [comment]
@rhuss yes that would be perfect!

**Comment by gsmet** [comment]
@rhuss sorry, F2F going on here, things are a bit crazy :)

So, yes, that's exactly what we wanted. Pointing to the source is not very stable as you could reorganize things for whatever reason. Having a published artifact gives us a totally stable URL where we can point to, and deal with the upgrades easily.

Thanks!

**Comment by rhuss** [comment]
Cool. I just released 1.3.5 which contains `run-java-sh-1.3.5-sh.sh` as direct artefact. Should bubble up soon to Maven central.

**Comment by rhuss** [comment]
BTW, adding the script with classifier was the only functional change compared to 1.3.4
